# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-LargeFileFetcher
version:      0.02
version_from: lib/WWW/LargeFileFetcher.pm
installdirs:  site
requires:
    LWP::UserAgent:                2.033
    Test::More:                    0.64

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
